# Generated by Django 4.1 on 2023-02-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDataTable',
            fields=[
                ('File', models.TextField(default=' ', primary_key=True, serialize=False)),
                ('To', models.TextField(default=' ')),
                ('From', models.TextField(default=' ')),
                ('Body', models.TextField(default=' ')),
                ('message', models.TextField(default=' ')),
                ('count', models.IntegerField(default=0)),
                ('IsPersonal', models.IntegerField(default=0)),
                ('category', models.TextField(default=' ')),
                ('lemma', models.TextField(default=' ')),
                ('preds_rf', models.TextField(default=' ')),
                ('topic', models.TextField(default=' ')),
                ('percentage', models.FloatField(default=0)),
                ('ManualClassify', models.TextField(default=' ')),
                ('ManualReason', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('coefficient', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RunClassifierData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_personal_emails', models.IntegerField(default=0)),
                ('accuracy_percentage', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TopicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.TextField(default=' ')),
                ('word', models.TextField(default=' ')),
                ('importance', models.FloatField(default=0)),
            ],
        ),
    ]
